added support for mahuika. sensitive information like passwords are stored in gpg

diff --git a/server/bin/slurm/submit_job b/server/bin/slurm/submit_job
--- a/server/bin/slurm/submit_job
+++ b/server/bin/slurm/submit_job
@@ -5,18 +5,18 @@ if [ "$#" != "1" ]; then
   exit 1
 fi
 
-jobfile=${1}
+job_file=${1}
 
-if [ ! -f ${jobfile} ]; then
-  echo "Error: Job description file ${jobfile} doesn't exist or is not a file" >&2
+if [ ! -f ${job_file} ]; then
+  echo "Error: Job description file ${job_file} doesn't exist or is not a file" >&2
   exit 1
 fi
 
-output=$(sbatch --export=NONE ${jobfile})
+output=$(sbatch --export=NONE ${job_file})
 rc=$?
 if [ "${rc}" != "0" ]; then
   exit 1
 fi
 
-jobid=$(echo $output | rev | cut -d\  -f1 | rev)
-echo ${jobid}
+job_id=$(echo ${output} | rev | cut -d\  -f1 | rev)
+echo ${job_id}
